leftnav:
- identifier: aace887d-7bcd-350c-ead7-2b23032a0664
  name: Syllabus
  url: /pages/syllabus
  weight: 10
- identifier: d440e948-7d65-1f5b-bb3a-7b61c145d962
  name: Readings
  url: /pages/readings
  weight: 20
- identifier: cb5386fa-ef13-133f-00ae-0fa9a6b2e2f7
  name: Assignments
  url: /pages/assignments
  weight: 30
